name: Hello World
author: Matej Rojko
descripton: Some description
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Matej
outputs:
  time: 
    description: 'The greeting time'
runs:
  using: 'node12'
  main: "dist/index.js"